### ISSUE TITLE
Missing expected methods for Glimmer `Element` interface.

### ISSUE THREAD

**Issue by rwjblue** [ember-fastboot/simple-dom#23]
The Glimmer project expects the [following interface](https://github.com/tildeio/glimmer/blob/08964897dd504f76c38dcae9d60f5785b91bfa14/packages/glimmer-runtime/lib/dom/interfaces.ts#L54-L65) to be satisfied by the underlying `element` instance that it uses:

```js
export interface Element extends Node {
  namespaceURI: string;
  tagName: string;
  firstChild: Node;
  lastChild: Node;
  removeAttribute(name: string): void;
  removeAttributeNS(namespaceURI: string, name: string);
  setAttribute(name: string, value: string): void;
  setAttributeNS(namespaceURI: string, qualifiedName: string, value: string): void;
  insertBefore(node: Node, reference: Node): void;
  removeChild(node: Node): void;
}
```

The `simple-dom` `Element` ([see here](https://github.com/ember-fastboot/simple-dom/blob/44e62f9314d0f45976d4fb338462a5a39e9222e1/lib/simple-dom/document/element.js)) does not implement the following methods:

* `removeAttributeNS`
* `setAttributeNS`

**Comment by krisselden** [comment]
@rwjblue it is also specifying createElementNS

**Comment by krisselden** [comment]
I think this maybe a oversight of glimmer 2, it used to be `element.setAttributeNS?(...)` and `document.createElementNS?(...)`

**Comment by bcardarella** [comment]
@krisselden but SimpleDOM would still require the `NS` functions, yes?

**Comment by krisselden** [comment]
@bcardarella namespaces shouldn't be part of that interface and the fix @rwjblue submitted is the correct one.  Serialization of these require prefixes, there is nothing I would do with the namespace url, and xmlns stuff is ignored by html.

**Comment by bcardarella** [comment]
@krisselden ok, thanks for jumping on this and weighing in 👍
