### ISSUE TITLE
Bundle simple-html-tokenizer

### ISSUE THREAD

**Issue by RangerMauve** [ember-fastboot/simple-dom#6]
By the looks of it, the html-parser part of this library relies on the [simple-html-tokenizer](https://github.com/tildeio/simple-html-tokenizer) library. Wouldn't it make sense to just bundle it with the parser, or maybe provide the parser as a separate module?

**Comment by krisselden** [comment]
To me it is more of a peer dependency, there is an issue of whether you want all the character entities.

**Comment by RangerMauve** [comment]
Is there a way to use the paser without the tokenizer?

**Comment by krisselden** [comment]
You can use the parser with different tokenizers.  Right now there are 2 tokenizer builds, one with all HTML5 character entities, and one with just https://github.com/tildeio/simple-html-tokenizer/blob/master/lib/simple-html-tokenizer/char-refs/min.js
