### ISSUE TITLE
documentService.body.firstChild not respecting other element in index.html

### ISSUE THREAD

**Issue by snewcomer** [ember-fastboot/simple-dom#70]
In FastBoot, it seems documentService.body.firstChild == `.ember-view` and not the expected `#ember-header`.  Lmk if I am missing something!

`app/index.html`
```html
<body>
<div id="ember-header"></div>
{{content-for "body"}}
```

1.3.0 version

![screen shot 2018-08-28 at 7 16 45 pm](https://user-images.githubusercontent.com/7374640/44761191-f1c9a180-aaf6-11e8-84e6-497af1b5fa7f.png)

**Comment by snewcomer** [comment]
Just realized that the scope for the `documentService.body` might just be the `application.hbs` and not the `index.html`.  Is this expected?

**Comment by krisselden** [comment]
While I know it’s confusing that doesn’t have to do with this library but how fastboot uses it. The app is rendered into an empty documented then pieces are serialized and placed into the index html
